---

extends: default

rules:
  comments:
    min-spaces-from-content: 1

  comments-indentation: disable

  document-start:
    ignore: |
      .github/*.yml

  indentation:
    spaces: consistent
    indent-sequences: consistent

  line-length: disable
