name: Super Linter

on:
  workflow_call:

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          CSS_FILE_NAME: "stylelint.config.js"
          # EDITORCONFIG_FILE_NAME: ".editorconfig-checker.json"
          FIX_CSS_PRETTIER: true
          FIX_ENV: true
          FIX_GRAPHQL_PRETTIER: true
          FIX_HTML_PRETTIER: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JSON_PRETTIER: true
          FIX_JSX_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_SHELL_SHFMT: true
          FIX_TSX: true
          FIX_TYPESCRIPT_PRETTIER: true
          FIX_YAML_PRETTIER: true
          # GITHUB_ACTIONS_CONFIG_FILE: "actionlint.yml"
          # GITLEAKS_CONFIG: ".gitleaks.toml"
          JAVASCRIPT_ES_CONFIG_FILE: "eslint.config.js"
          # MARKDOWN_CONFIG_FILE: ".markdown-lint.yml"
          # NATURAL_LANGUAGE_CONFIG_FILE: "textlintrc.js"
          PRETTIER_CONFIG: "prettier.config.js"
          TYPESCRIPT_ES_CONFIG_FILE: "eslint.config.js"
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: ${DEFAULT_WORKSPACE}/tsconfig.json
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_ENV: true
          VALIDATE_GIT_COMMITLINT: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GRAPHQL_PRETTIER: true
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_JSX_PRETTIER: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_YAML_PRETTIER: true
