name: Audit

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.x

      - run: npm ci

  bundle-size:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: jackyef/bundlewatch-gh-action@0.3.0
        id: audit-bundle-size
        with:
          build-script: npm run build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
