name: Audit

# @TODO: add in more things like:
# - [ ] dead css checks

on: # yamllint disable-line rule:truthy
  - push

jobs:
  bundle-size:
    name: Audit the bundle size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        name: Setup Node.js @v20
        with:
          cache: npm
          node-version: 20.x

      - run: npm ci
        name: Install dependencies

      - uses: jackyef/bundlewatch-gh-action@0.3.0
        name: Analyze using BundleWatch
        with:
          build-script: npm run build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}

  performance:
    name: Audit the performance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        name: Setup Node.js @v20
        with:
          cache: npm
          node-version: 20.x

      - run: npm ci
        name: Install dependencies

      - run: npm install -g @lhci/cli@0.14.x
        name: Install Lighthouse CLI

      - run: npm run build
        name: Build project

      - run: lhci autorun
        name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
