name: Audit

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.x

      - run: npm ci

  bundle-size:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - id: audit-bundle-size
        name: Check bundle size
        uses: ./.github/workflows/bundlewatch.workflow.yml
