name: Audit

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  setup:
    uses: ./.github/workflows/common/setup.yml
    with:
      cache-key: ${{ runner.os }}-npm-v1-${{ hashFiles('**/package-lock.json') }}

  bundle-size:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - id: audit-bundle-size
        name: Check bundle size
        uses: ./.github/workflows/common/bundlewatch.yml
