name: Audit

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  setup:
    uses: ./.github/workflows/setup.workflow.yml

  bundle-size:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - id: audit-bundle-size
        name: Check bundle size
        uses: ./.github/workflows/bundlewatch.workflow.yml
