name: Changesets

on:
  workflow_call:

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Changeset PR
        uses: changesets/action@v1
        with:
          commit: "chore(release): 🦋 version packages"
          publish: npx changeset publish
          title: "chore(release): 🦋 version packages"
          version: npx changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
