name: Chromatic

on:
  workflow_call:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          buildScriptName: build:storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
