name: Deploy

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-github-pages.outputs.page_url }}
    steps:
      - id: deploy-github-pages
        name: Deploy to GitHub Pages
        uses: ./.github/workflows/common/storybook.yml
