name: Deploy

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  github-pages:
    name: Publish Storybook to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        id: deploy-github-pages
        name: Publish Storybook to GitHub Pages
        with:
          build_command: npm run build:storybook
          install_command: npm ci
          path: storybook-static
    environment:
      name: github-pages
      url: ${{ steps.deploy-github-pages.outputs.page_url }}
