name: Label

on:
  - pull_request_target

jobs:
  label:
    name: Label Pull Requests
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
  alex:
    name: Check language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v4
        name: Setup Node.js @v20
        with:
          cache: npm
          node-version: 20.x

      - uses: brown-ccv/alex-recommends@v1.2.1
        name: Comment on new PR
        with:
          message_id: 'alex'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
