name: Label

on:
  - pull_request_target

jobs:
  label:
    name: Label Pull Requests
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
