name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  super-lint:
    permissions:
      # To write linting fixes
      contents: write
      # To write Super-linter status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          CSS_FILE_NAME: "${DEFAULT_WORKSPACE}/stylelint.config.js"
          # EDITORCONFIG_FILE_NAME: ".editorconfig-checker.json"
          FIX_CSS_PRETTIER: true
          FIX_ENV: true
          FIX_GRAPHQL_PRETTIER: true
          FIX_HTML_PRETTIER: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JSON_PRETTIER: true
          FIX_JSX_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_SHELL_SHFMT: true
          FIX_TSX: true
          FIX_TYPESCRIPT_PRETTIER: true
          FIX_YAML_PRETTIER: true
          # GITHUB_ACTIONS_CONFIG_FILE: "${DEFAULT_WORKSPACE}/actionlint.yml"
          # GITLEAKS_CONFIG: "${DEFAULT_WORKSPACE}/.gitleaks.toml" # Path to your Gitleaks config if you have one
          JAVASCRIPT_ES_CONFIG_FILE: "${DEFAULT_WORKSPACE}/eslint.config.js"
          # MARKDOWN_CONFIG_FILE: ".markdown-lint.yml"
          # NATURAL_LANGUAGE_CONFIG_FILE: "textlintrc.js"
          PRETTIER_CONFIG: "${DEFAULT_WORKSPACE}/prettier.config.js"
          TYPESCRIPT_ES_CONFIG_FILE: "${DEFAULT_WORKSPACE}/eslint.config.js"
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: ${DEFAULT_WORKSPACE}/tsconfig.json
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_ENV: true
          VALIDATE_GIT_COMMITLINT: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GRAPHQL_PRETTIER: true
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_JSX_PRETTIER: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_YAML_PRETTIER: true

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
