name: Publish

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    name: Version using Semantic Versioning
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          # The short ref name of the branch or tag that triggered
          #  the workflow run. For example, `main` or `1.x`
          target-branch: ${{ github.ref_name }}

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: actions/setup-node@v4
        name: Setup Node.js @v20
        with:
          cache: npm
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        name: Install dependencies

      - run: npm publish
        name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gh:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: actions/setup-node@v4
        name: Setup Node.js @v20
        with:
          cache: npm
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@theholocron'

      - run: npm ci
        name: Install dependencies

      - run: npm publish --access public
        name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
