name: Publish

on: # yamllint disable-line rule:truthy
  release:
    types:
      - published

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          cache: npm
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        name: Install dependencies

      - run: npm publish
        name: Publish to GitHub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gh:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: actions/setup-node@v4
        name: Setup Node.js @v20
        with:
          cache: npm
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@theholocron'

      - run: npm ci
        name: Install dependencies

      - run: npm publish --access public
        name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
