name: Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changeset-release:
    name: Create a release
    permissions:
      contents: write # to create release
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - uses: changesets/action@v1
        name: Create a Changeset PR
        with:
          commit: "chore(release): 🦋 version packages"
          publish: npx changeset publish
          title: "chore(release): 🦋 version packages"
          version: npx changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
