name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    uses: ./.github/workflows/common/setup.yml
    with:
      cache-key: ${{ runner.os }}-npm-v1-${{ hashFiles('**/package-lock.json') }}

  npm:
    needs: setup
    permissions:
      contents: write # to create release
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - id: release-npm
        name: Publish to NPM
        uses: ./.github/workflows/common/changesets.yml
