name: "Setup"

on:
  workflow_call:
    inputs:
      fetch-depth:
        default: 1 # Default fetch depth (shallow clone)
        description: "Git fetch depth"
        required: false
        type: number

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs['fetch-depth'] }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
