name: Version

# @TODO: check if this could replace changesets
# if so, i can get rid of the publish command and changesets

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Version using Semantic Versioning
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          # The short ref name of the branch or tag that triggered
          #  the workflow run. For example, `main` or `1.x`
          target-branch: ${{ github.ref_name }}

      # The logic below handles the npm publication:
      # - uses: actions/checkout@v4
      #   name: Checkout repository
      #   # these if statements ensure that a publication only occurs when
      #   # a new release is created:
      #   if: ${{ steps.release.outputs.release_created }}

      # - uses: actions/setup-node@v4
      #   name: Setup Node.js @v20
      #   if: ${{ steps.release.outputs.release_created }}
      #   with:
      #     cache: npm
      #     node-version: 20.x
      #     registry-url: 'https://registry.npmjs.org'

      # - run: npm ci
      #   name: Install dependencies
      #   if: ${{ steps.release.outputs.release_created }}

      # - run: npm publish
      #   name: Publish to NPM
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #   if: ${{ steps.release.outputs.release_created }}

      # - run: npm publish
      #   name: Publish to GitHub Packages
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   if: ${{ steps.release.outputs.release_created }}
